### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print' when installing?

### ISSUE THREAD

**Issue by andreimoment** [orestis/pysmell#10]
When running 

```
me@my-mbp pysmell-0.7.3 % python3 setup.py install
```

I received this error

```
 File "/Users/andrei/Downloads/pysmell-0.7.3/setup.py", line 27
    print post_install_message
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(post_install_message)?
```

I am new to python and I just installed python3 on Catalina via brew. 

I am presuming I'm doing something wrong or missing something as it is unlikely for the package to be un-installable. 

Could someone point me in the right direction to successfully installing pysmell? 

Thank you!

**Comment by orestis** [comment]
Sorry to waste your time. This project is more than 10 years old. I haven’t used Python in years. I’m sure there are better alternatives than pysmell. Good luck!
